version: 1.0
pipeline:
  test:
    in:
      - "**/*.go"
    exec: go test -v -count=1 ./...
  build:
    in:
      - "**/*.go"
    exec: bash -c 'go build -ldflags "-X github.com/tivvit/yap/cmd.GitTag=$(git describe --tags 2>1 || echo "unknown") -X github.com/tivvit/yap/cmd.GitCommit=$(git rev-parse --short HEAD)" .'
    out:
      - yap
  install:
    deps:
      - build
    exec: cp yap /usr/local/bin/