version: 1.0
pipeline:
  test:
    in:
      - "**/*.go"
    exec: go test -v -count=1 ./...
  git-tag:
    idempotent: false
    exec: bash -c 'git describe --tags 2>&1 > tag || echo "unknown" > tag'
    out:
      - tag
  git-commit:
    idempotent: false
    exec: bash -c 'git rev-parse --short HEAD > commit'
    out:
      - commit
  build:
    in:
      - "**/*.go"
      - tag
      - commit
    exec: bash -c 'go build -ldflags "-X github.com/tivvit/yap/cmd.GitTag=$(cat tag) -X github.com/tivvit/yap/cmd.GitCommit=$(cat commit)" .'
    out:
      - yap
  install:
    in:
      - yap
    exec: echo "sudo cp yap /usr/local/bin/"