version: 1.0
pipeline:
  test:
    in:
      - "**/*.go"
    exec: go test -v -count=1 ./...
  build:
    in:
      - "**/*.go"
    exec: go build .
    out:
      - yap
  install:
    deps:
      - build
    exec: cp yap /usr/local/bin/