version: 1.0
pipeline:
  buffered:
    exec: "python3 print-wait.py"
    idempotent: false
  unbuffered:
    exec: "python3 -u print-wait.py"
    idempotent: false
  buffered-stdout:
    exec: "python3 print-stdout.py"
    idempotent: false
  buffered-stderr:
    exec: "python3 print-stderr.py"
    idempotent: false