version: 1.0
pipeline:
  run-always:
    exec: ls
    check: bash -c 'cat /dev/urandom | head -c 20'
  idempotent:
    exec: ls
    idempotent: false
  run-once:
    exec: ls
    check: echo "a"
  run-external-dep:
    exec: ls
    check: bash -c 'curl -LIs ubuntu.com | grep -i "Content-Length:"'