name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: test
      run: go test -v ./...
    
    - name: vet
      run: go vet ./...
  
    - name: Build
      run: go build -v .
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: yap
        path: ./yap

